version: '3.3'
services:
     transmissionbot:
        image: 'tdelorge/transmissionbotdiscord'
        container_name: transmissionbot
        volumes:
            - 'path/to/config.json:/TransmissionBot/config.json:rw'
        restart: unless-stopped